# Generated by Django 2.1.4 on 2019-01-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='create',
            new_name='created',
        ),
    ]
