# Generated by Django 2.1.4 on 2019-01-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190127_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionpersonal',
            name='link_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='link_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informacionpersonal',
            name='link_instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
